### ISSUE TITLE
Nullability Support

### ISSUE THREAD

**Issue by hopeman15** [HelloCuriosity/model-forge#72]
Some of the types aren't auto generating when nullable:

- Boolean
- Double
- Float
- Int
- Long

This is the exception that is being thrown.
```
java.lang.reflect.InvocationTargetException
org.objenesis.ObjenesisException: java.lang.reflect.InvocationTargetException
	at org.objenesis.instantiator.sun.SunReflectionFactoryHelper.newConstructorForSerialization(SunReflectionFactoryHelper.java:48)
	at org.objenesis.instantiator.sun.SunReflectionFactoryInstantiator.<init>(SunReflectionFactoryInstantiator.java:41)
	at org.objenesis.strategy.StdInstantiatorStrategy.newInstantiatorOf(StdInstantiatorStrategy.java:68)
	at org.objenesis.ObjenesisBase.getInstantiatorOf(ObjenesisBase.java:94)
```

**Comment by hopeman15** [comment]
superseded by https://github.com/HelloCuriosity/model-forge/issues/73
